import 'package:flutter/foundation.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/cart_item.dart';
import '../models/product.dart';
import '../models/order_model.dart';
import 'reservation_service.dart';
import 'client_service.dart';

class CartService extends ChangeNotifier {
  static final CartService _instance = CartService._internal();
  factory CartService() => _instance;
  CartService._internal();

  final List<CartItem> _items = [];
  double _couponDiscount = 0;
  String? _appliedCouponCode;
  final ClientService _clientService = ClientService();

  List<CartItem> get items => _items;

  int get itemCount => _items.fold(0, (sum, item) => sum + item.quantity);

  double get subtotal => _items.fold(0, (sum, item) => sum + item.total);
  
  double get discount => _couponDiscount;
  
  double get total => (subtotal - _couponDiscount) < 0 ? 0 : (subtotal - _couponDiscount);

  String? get currentPymeId {
    if (_items.isEmpty) return null;
    return _items.first.product.pymeId;
  }

  Future<void> addToCart(Product product, {DateTime? scheduledTime}) async {
    // Check if product is from the same store
    if (_items.isNotEmpty && _items.first.product.pymeId != product.pymeId) {
      throw Exception('Solo puedes agregar productos de una misma tienda.');
    }

    // Find item with same product ID AND same scheduled time (if any)
    final index = _items.indexWhere((item) => 
      item.product.id == product.id && item.scheduledTime == scheduledTime
    );

    if (index != -1) {
      if (scheduledTime != null) {
        throw Exception('Ya tienes este horario reservado en tu carrito.');
      }
      _items[index].quantity++;
    } else {
      if (scheduledTime != null) {
        // Try to book the slot globally
        try {
          final userId = FirebaseAuth.instance.currentUser?.uid ?? 'guest';
          await ReservationService().bookSlot(product.pymeId, product.id, userId, scheduledTime);
        } catch (e) {
          rethrow; // Propagate error (e.g. "Slot taken")
        }
      }
      _items.add(CartItem(product: product, scheduledTime: scheduledTime));
    }
    notifyListeners();
  }

  Future<void> removeFromCart(Product product, {DateTime? scheduledTime}) async {
    final index = _items.indexWhere((item) => 
      item.product.id == product.id && item.scheduledTime == scheduledTime
    );
    if (index != -1) {
      if (_items[index].quantity > 1) {
        _items[index].quantity--;
      } else {
        // If removing the item completely, release the reservation if it exists
        if (scheduledTime != null) {
          await ReservationService().cancelReservation(product.id, scheduledTime);
        }
        _items.removeAt(index);
      }
      // If cart becomes empty, reset coupon
      if (_items.isEmpty) {
        _couponDiscount = 0;
        _appliedCouponCode = null;
      }
      notifyListeners();
    }
  }

  Future<void> clearCart() async {
    // Release all reservations (User abandoned cart)
    for (var item in _items) {
      if (item.scheduledTime != null) {
        await ReservationService().cancelReservation(item.product.id, item.scheduledTime!);
      }
    }
    _items.clear();
    _couponDiscount = 0;
    _appliedCouponCode = null;
    notifyListeners();
  }

  Future<void> checkout() async {
    if (_items.isEmpty) return;

    final order = OrderModel(
      id: '', // Will be generated by Firestore
      clientId: FirebaseAuth.instance.currentUser?.uid ?? '',
      pymeId: currentPymeId ?? '',
      items: _items.map((item) => OrderItem(
        productId: item.product.id,
        productName: item.product.name,
        quantity: item.quantity,
        price: item.product.price,
        total: item.total,
        scheduledTime: item.scheduledTime,
      )).toList(),
      subtotal: subtotal,
      discount: _couponDiscount,
      total: total,
      couponCode: _appliedCouponCode,
      status: 'pending',
      createdAt: DateTime.now(),
    );

    await _clientService.createOrder(order);

    // Confirm purchase. Reservations remain 'confirmed' (or 'pending' -> 'confirmed').
    // We do NOT cancel them.
    _items.clear();
    _couponDiscount = 0;
    _appliedCouponCode = null;
    notifyListeners();
  }

  bool applyCoupon(String code, double amount) {
    // Condition: Single store (already enforced by addToCart)
    if (_items.isEmpty) return false;

    // Condition: Coupon not already used (Mock check)
    if (_appliedCouponCode == code) return false;

    // Condition: "All or nothing" logic is handled in the total calculation.
    // If total < coupon, the user "loses" the difference, effectively using the whole coupon.
    
    _couponDiscount = amount;
    _appliedCouponCode = code;
    notifyListeners();
    return true;
  }
}
