// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHiwY8g2klbEy26z80UaxzIlqtIT8YQuQ',
    appId: '1:527081578254:web:58ab406c05a99131b4415f',
    messagingSenderId: '527081578254',
    projectId: 'soyplus-fec46',
    authDomain: 'soyplus-fec46.firebaseapp.com',
    storageBucket: 'soyplus-fec46.firebasestorage.app',
    measurementId: 'G-J50MEKK74K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQJgrcK3ANPU6aFTGlK4ZYQi84ut2dWmI',
    appId: '1:527081578254:android:c4764c1627502218b4415f',
    messagingSenderId: '527081578254',
    projectId: 'soyplus-fec46',
    storageBucket: 'soyplus-fec46.firebasestorage.app',
  );
}
